name: CI

on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    env:
      GOO_API_KEY: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.3.app/Contents/Developer'
    - name: Show Devices List
      run: xcrun instruments -s
    - name: SwiftLint
      run: brew install swiftlint && swiftlint
    - name: Build # シミュレーター向け
      run: xcodebuild -sdk iphonesimulator -configuration Debug build goo_id=GOO_API_KEY